// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

const db_url = `mysql://${env("PRISMA_USER_NAME")}:${env("PRISMA_USER_PASSWORD")}@${env("DATABASE_HOST")}:${env("DATABASE_PORT")}/${env("DATABASE_NAME")}?schema=public&connect_timeout=30&pool_timeout=30&socket_timeout=30`
console.log(db_url);

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: db_url,
  },
});
